### PR TITLE
Added French translation

### PR DESCRIPTION
**Pull request by Micks29**

### CODE REVIEW

**Comment by fasteque** [comment]
Thanks a lot for the french translation! Before merging it, I'd like to ask you about the string in the "Swatches" section because these are not translated: did you miss them or it was intentional?

**Comment by Micks29** [comment]
@fasteque you're welcome! Yes it's intentional I've no idea (for now) for about translation for "Swatches" section.
I've noticed it miss strings related with arrays.xml so can you add them in strings.xml or I must translate arrays.xml too?

**Comment by fasteque** [comment]
@Micks29 if you duplicate the file ```arrays.xml``` in the same way you did for the strings and just change the values of the items it should work.

**Comment by Micks29** [comment]
Ok done!

**Comment by fasteque** [comment]
Merged!

**Pull request merged**
